### ISSUE TITLE
Won't build on openjdk8

### ISSUE THREAD

**Issue by stain** [jai-imageio/jai-imageio-jpeg2000#1]
The [travis build of jai-imageio-jpeg2000 on openjdk8](https://travis-ci.org/stain/jai-imageio-jpeg2000/jobs/35120568) fails with:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project jai-imageio-jpeg2000: Compilation failure
[ERROR] Failure executing javac, but could not parse the error:
[ERROR] An exception has occurred in the compiler (1.8.0_05). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
[ERROR] java.lang.AssertionError
[ERROR] at com.sun.tools.javac.util.Assert.error(Assert.java:126)
[ERROR] at com.sun.tools.javac.util.Assert.check(Assert.java:45)
[ERROR] at com.sun.tools.javac.jvm.ClassWriter.writeCode(ClassWriter.java:1189)
[ERROR] at com.sun.tools.javac.jvm.ClassWriter.writeMethod(ClassWriter.java:1110)
[ERROR] at com.sun.tools.javac.jvm.ClassWriter.writeMethods(ClassWriter.java:1602)
[ERROR] at com.sun.tools.javac.jvm.ClassWriter.writeClassFile(ClassWriter.java:1692)
[ERROR] at com.sun.tools.javac.jvm.ClassWriter.writeClass(ClassWriter.java:1620)
[ERROR] at com.sun.tools.javac.main.JavaCompiler.genCode(JavaCompiler.java:749)
[ERROR] at com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1570)
[ERROR] at com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1534)
[ERROR] at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:904)
[ERROR] at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:863)
[ERROR] at com.sun.tools.javac.main.Main.compile(Main.java:523)
[ERROR] at com.sun.tools.javac.main.Main.compile(Main.java:381)
[ERROR] at com.sun.tools.javac.main.Main.compile(Main.java:370)
[ERROR] at com.sun.tools.javac.main.Main.compile(Main.java:361)
[ERROR] at com.sun.tools.javac.Main.compile(Main.java:74)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:483)
[ERROR] at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcess0(JavacCompiler.java:551)
[ERROR] at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcess(JavacCompiler.java:526)
[ERROR] at org.codehaus.plexus.compiler.javac.JavacCompiler.compile(JavacCompiler.java:167)
[ERROR] at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:678)
[ERROR] at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:128)
[ERROR] at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[ERROR] at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
[ERROR] at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
[ERROR] at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
[ERROR] at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
[ERROR] at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:483)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] -> [Help 1]
[ERROR] 
```

**Comment by sec13b** [comment]
@stain can you upload jdk-8u20-linux-x64.tar.gz
