### ISSUE TITLE
Image Writer is not avilable

### ISSUE THREAD

**Issue by montano1991** [jai-imageio/jai-imageio-jpeg2000#10]
Exception in thread "main" org.dcm4che2.data.ConfigurationError: No Image Writer of class com.sun.media.imageioimpl.plugins.jpeg2000.J2KImageWriterCodecLib available for format:jpeg2000
	at org.dcm4che2.imageio.ImageWriterFactory.getWriterForTransferSyntax(ImageWriterFactory.java:94)
	at org.dcm4che2.imageioimpl.plugins.dcm.DicomImageWriter.setupWriter(DicomImageWriter.java:219)
	at org.dcm4che2.imageioimpl.plugins.dcm.DicomImageWriter.prepareWriteSequence(DicomImageWriter.java:243)
	at org.dcm4che2.tool.dcm2dcm.Dcm2Dcm.recodeImages(Dcm2Dcm.java:427)
	at ChangeTransferSyntax.compressor(ChangeTransferSyntax.java:80)
	at ChangeTransferSyntax.main(ChangeTransferSyntax.java:27)

**Comment by stain** [comment]
You didn't provide any of your `org.dcm4che2` code, so I don't know what you are trying to do..

Are you sure you are picking up a [release of this forked jpeg2000](https://github.com/jai-imageio/jai-imageio-jpeg2000#usage) or trying to use the original java.net distribution? 

The class name should now be 
[com.github.jaiimageio.jpeg2000.impl.J2KImageWriter](https://github.com/jai-imageio/jai-imageio-jpeg2000/blob/master/src/main/java/com/github/jaiimageio/jpeg2000/impl/J2KImageWriter.java) which should be discoverable through the SPI.
